version: "3.8"

services:
  web:
    #image: node:12-alpine
    #command: sh -c "yarn install && yarn start"
    #command: sh -c "yarn create react-app reactnd-contacts-app && yarn add prop-types"
    build: .
    ports:
      - 80:80
    working_dir: /usr/share/nginx/html
    volumes:
      - ./:/usr/share/nginx/html:consistent
    stdin_open: true

